# Generated by Django 5.1.4 on 2025-01-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_alter_socialuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='gender',
        ),
    ]
