# Generated by Django 5.1.4 on 2025-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_remove_socialuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Seller', 'Seller')], default='Author', max_length=6),
        ),
    ]
