# Generated by Django 5.1.4 on 2025-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
